Traceback (most recent call last):
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/client.py", line 646, in async_setup_kernel
    yield
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/uni/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
proc = CrawlerProcess()
proc.crawl(followSpider)
proc.start()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mReactorNotRestartable[0m                     Traceback (most recent call last)
Cell [0;32mIn [32], line 3[0m
[1;32m      1[0m proc [38;5;241m=[39m CrawlerProcess()
[1;32m      2[0m proc[38;5;241m.[39mcrawl(followSpider)
[0;32m----> 3[0m [43mproc[49m[38;5;241;43m.[39;49m[43mstart[49m[43m([49m[43m)[49m

File [0;32m~/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/scrapy/crawler.py:363[0m, in [0;36mCrawlerProcess.start[0;34m(self, stop_after_crawl, install_signal_handlers)[0m
[1;32m    361[0m tp[38;5;241m.[39madjustPoolsize(maxthreads[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39msettings[38;5;241m.[39mgetint([38;5;124m'[39m[38;5;124mREACTOR_THREADPOOL_MAXSIZE[39m[38;5;124m'[39m))
[1;32m    362[0m reactor[38;5;241m.[39maddSystemEventTrigger([38;5;124m'[39m[38;5;124mbefore[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mshutdown[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39mstop)
[0;32m--> 363[0m [43mreactor[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43minstallSignalHandlers[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m

File [0;32m~/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/twisted/internet/base.py:1317[0m, in [0;36m_SignalReactorMixin.run[0;34m(self, installSignalHandlers)[0m
[1;32m   1316[0m [38;5;28;01mdef[39;00m [38;5;21mrun[39m([38;5;28mself[39m, installSignalHandlers: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mTrue[39;00m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[0;32m-> 1317[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstartRunning[49m[43m([49m[43minstallSignalHandlers[49m[38;5;241;43m=[39;49m[43minstallSignalHandlers[49m[43m)[49m
[1;32m   1318[0m     [38;5;28mself[39m[38;5;241m.[39mmainLoop()

File [0;32m~/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/twisted/internet/base.py:1299[0m, in [0;36m_SignalReactorMixin.startRunning[0;34m(self, installSignalHandlers)[0m
[1;32m   1290[0m [38;5;124;03m"""[39;00m
[1;32m   1291[0m [38;5;124;03mExtend the base implementation in order to remember whether signal[39;00m
[1;32m   1292[0m [38;5;124;03mhandlers should be installed later.[39;00m
[0;32m   (...)[0m
[1;32m   1296[0m [38;5;124;03m    installed during startup.[39;00m
[1;32m   1297[0m [38;5;124;03m"""[39;00m
[1;32m   1298[0m [38;5;28mself[39m[38;5;241m.[39m_installSignalHandlers [38;5;241m=[39m installSignalHandlers
[0;32m-> 1299[0m [43mReactorBase[49m[38;5;241;43m.[39;49m[43mstartRunning[49m[43m([49m[43mcast[49m[43m([49m[43mReactorBase[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[43m)[49m

File [0;32m~/Desktop/Lehre/python_class/venv.nosync/lib/python3.11/site-packages/twisted/internet/base.py:843[0m, in [0;36mReactorBase.startRunning[0;34m(self)[0m
[1;32m    841[0m     [38;5;28;01mraise[39;00m error[38;5;241m.[39mReactorAlreadyRunning()
[1;32m    842[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_startedBefore:
[0;32m--> 843[0m     [38;5;28;01mraise[39;00m error[38;5;241m.[39mReactorNotRestartable()
[1;32m    844[0m [38;5;28mself[39m[38;5;241m.[39m_started [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    845[0m [38;5;28mself[39m[38;5;241m.[39m_stopped [38;5;241m=[39m [38;5;28;01mFalse[39;00m

[0;31mReactorNotRestartable[0m: 
ReactorNotRestartable: 

